<a href="https://colab.research.google.com/github/kckohkoh2/fantastic-disco/blob/master/day0115.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
h=np.array([[1,0,0,1,2],
            [1,0,0,0,1],
            [1,1,0,0,1]])
hd=np.array([1,0,0,0,2])
c1=np.dot(h,hd)
c2=np.inner(h,hd)


[5 3 3] [5 3 3]


In [6]:
import numpy as np
a=[3,2,0]
b=[0,5,0]
c=np.inner(a,b)
d=np.outer(a,b)
e=np.dot(a,b)
f=np.cross(a,b)
print(c)
print(d)
print(e)
print(f)

10
[[ 0 15  0]
 [ 0 10  0]
 [ 0  0  0]]
10
[ 0  0 15]


In [12]:
import numpy as np
a=np.array([2,4,0])
b=np.array([3,1,0])
cross_ab=np.cross(a,b)
s=np.linalg.norm(cross_ab)
print(s/2)

5.0


In [7]:
import numpy as np
a=[1,4,0]
b=[2,-5,0]
f=np.cross(a,b)
print(np.dot(a,f))
print(np.dot(b,f))

0
0


In [ ]:
a

In [ ]:
def softmax(a):
    exp_a=np.exp(a)
    sum_exp_a=np.sum(exp_a)
    y=exp_a/sum_exp_a
    return y
c1_sm=softmax(c1)
print(c1_sm)
print(np.sum(c1_sm))

[0.78698604 0.10650698 0.10650698]
1.0


In [14]:
import math
a=3;b=4;c=6
A1=math.sqrt(4*a**2*c**2-(a**2+c**2-b**2)**2)/4
S=(a+b+c)/2
A2=math.sqrt(S*(S-a)*(S-b)*(S-c))
print(A1,A2)

5.332682251925386 5.332682251925386


In [2]:
import math
import numpy as np
a=3;b=4;c=5
a_v=[a,0]
theta=math.acos((a**2+c**2-b**2)/(2*a*c))
c_v=[c*math.cos(theta),c*math.sin(theta)]
cross_ac=np.cross(a_v,c_v)
S=np.linalg.norm(cross_ac)/2
print(S)

6.0


식(21)을 이용하는 방법

In [86]:
import math
a=3;b=4;c=6;d=4;e=6;f=7
cx=(a**2+c**2-b**2)/(2*a)
cy=math.sqrt(c**2-cx**2)
#cy=math.sqrt(c**2-((a**2+c**2-b**2)/(2*a))**2)
dx=(a**2+d**2-e**2)/(2*a)
dy=(c**2+d**2-f**2-2*cx*dx)/(2*cy)
h=math.sqrt(d**2-(dx**2+dy**2))
V=1/6*a*cy*h
print(dy)
print(V)

2.914418285667646
3.6190084584347466


식(22)를 이용하는 방법

In [77]:
import math
import numpy as np
a=3;b=4;c=6;d=4;e=6;f=7
cy=math.sqrt(c**2-((a**2+c**2-b**2)/(2*a))**2)
cx=(a**2+c**2-b**2)/(2*a)
dx=(a**2+d**2-e**2)/(2*a)
dy=(a*(c**2+d**2-f**2)-cx*(a**2+d**2-e**2))/(2*cy*a)
h=math.sqrt(d**2-(dx**2+dy**2))
V=1/6*a*cy*h
print(dy)
print(V)

2.914418285667646
3.6190084584347466


식(23)을 이용하는 방법

In [87]:
import math
import numpy as np
a=3;b=4;c=6;d=4;e=6;f=7
cy=math.sqrt(c**2-((a**2+c**2-b**2)/(2*a))**2)
cx=(a**2+c**2-b**2)/(2*a)
dy=((2*a**2*(c**2+d**2-f**2)-(a**2+c**2-b**2)*(a**2+d**2-e**2))
    /(2*a*math.sqrt(4*a**2*c**2-(a**2+c**2-b**2)**2)))
dx=(a**2+d**2-e**2)/(2*a)
h=math.sqrt(d**2-(dx**2+dy**2))
V=1/6*a*cy*h
print(dy)
print(V)

2.9144182856676464
3.6190084584347453


벡터곱과 내적곱을 이용하는 방법

In [84]:
import numpy as np
A=np.array([a,0,0])
C=np.array([cx,cy,0])
D=np.array([dx,dy,h])
V=1/6*np.dot(np.cross(A,C),D)
print(V)

3.6190084584347453


Travkin의 방법

In [85]:
import math
a=3;b=4;c=6;d=4;e=6;f=7
u=d;v=e;w=f;U=b;V=c;W=a
X=(w-U+v)*(U+v+w)
Y=(u-V+w)*(V+w+u)
Z=(v-W+u)*(W+u+v)
x=(U-v+w)*(v-w+U)
y=(V-w+u)*(w-u+V)
z=(W-u+v)*(u-v+W)
a=math.sqrt(x*Y*Z)
b=math.sqrt(y*Z*X)
c=math.sqrt(z*X*Y)
d=math.sqrt(x*y*z)
V=math.sqrt((-a+b+c+d)*(a-b+c+d)*(a+b-c+d)*(a+b+c-d))/(192*u*v*w)
print(V)

3.619008458434743
