<a href="https://colab.research.google.com/github/kckohkoh2/fantastic-disco/blob/master/day1025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Broadcasting

In [1]:
import torch
t0=torch.IntTensor([3]) #scalar
t1=torch.IntTensor([1,2,4]) #1D tensor
t2=torch.IntTensor([[1,2,3],[4,5,6]])
m1=t0+t1 #t0 is broadcasted to t1
m2=t1+t2 #t1 is broadcasted to t2
print(m1)
print(m2)
# PyTorch로 시작하는 딥 러닝 입문(1) - 소개|작성자 Alpha Koh

tensor([4, 5, 7], dtype=torch.int32)
tensor([[ 2,  4,  7],
        [ 5,  7, 10]], dtype=torch.int32)


 행렬곱(Matrix Multiplication)

In [2]:
import torch
m1=torch.IntTensor([[1,2],[3,4]])
m2=torch.IntTensor([[1],[2]])
print(m1.shape)
print(m2.shape)
print(m1.matmul(m2))
print(torch.mm(m1,m2))
#PyTorch로 시작하는 딥 러닝 입문(1) - 소개|작성자 Alpha Koh

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[ 5],
        [11]], dtype=torch.int32)
tensor([[ 5],
        [11]], dtype=torch.int32)
